name: tiengviet
version: 0.5.0
description: >-
  ðŸ‡»ðŸ‡³ Converts vietnamese language sign to unsigned easily. ðŸ˜
  Give me a string vietnamese language, i will respond you string vietnamese unsigned. ðŸ‘
homepage: https://github.com/tvc12/tiengviet
repository: https://github.com/tvc12/tiengviet
documentation: https://github.com/tvc12/tiengviet
issue_tracker: https://github.com/tvc12/tiengviet/issues
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: 1.16.8
  pedantic: 1.11.0
