name: tiengviet
version: 0.2.0
description: >-
  ğŸ‡»ğŸ‡³ CÃ´ng cá»¥ chuyá»ƒn Ä‘á»•i Tiáº¿ng Viá»‡t cÃ³ dáº¥u sang khÃ´ng dáº¥u má»™t cÃ¡ch dá»… dÃ ng.
author: Vi Chi Thien <thienvc12.it@gmail.com>
homepage: https://github.com/tvc12/tiengviet
repository: https://github.com/tvc12/tiengviet
documentation: https://github.com/tvc12/tiengviet
issue_tracker: https://github.com/tvc12/tiengviet/issues
environment:
  sdk: '>=1.19.0 <3.0.0'
dev_dependencies:
  test: ^1.0.0